services:
  - type: web
    name: trendspotter-backend
    runtime: python
    buildCommand: ""
    startCommand: uvicorn src.api.recommendation_api:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
