from setuptools import setup, find_packages

setup(
    name="trendspotter",
    version="0.1.0",
    description="A localized recommendation engine for visual content discovery in Toronto",
    author="Your Name",
    author_email="your.email@example.com",
    packages=find_packages(),
    install_requires=[
        "pandas>=2.0.0",
        "numpy>=1.24.0",
        "scipy>=1.11.0",
        "scrapy>=2.8.0",
        "beautifulsoup4>=4.12.0",
        "requests>=2.31.0",
        "sqlalchemy>=2.0.0",
        "psycopg2-binary>=2.9.0",
        "pymongo>=4.6.0",
        "scikit-learn>=1.3.0",
        "tensorflow>=2.15.0",
        "torch>=2.1.0",
        "fastapi>=0.104.0",
        "uvicorn>=0.24.0",
        "pytest>=7.4.0",
        "black>=23.10.0",
        "isort>=5.12.0",
        "flake8>=6.1.0",
        "matplotlib>=3.8.0",
        "seaborn>=0.13.0",
        "plotly>=5.18.0",
        "python-dotenv>=1.0.0",
    ],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
    python_requires=">=3.9",
)